" プラグインが実際にインストールされるディレクトリ
let s:dein_dir = expand('~/.dein')
" dein.vim 本体
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

" dein.vim がなければ github から落としてくる
if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

let g:Powerline_symbols = 'fancy'
set laststatus=2

set encoding=utf-8
"scriptencoding utf-8

" 行番号を表示 
set number 
" 検索語を強調表示
set hlsearch

" キーマップ：検索ハイライトの解除
nnoremap <ESC><ESC> :<C-u>nohlsearch<CR>

" 検索時に大文字・小文字を区別しない
set ignorecase
" カーソル行を強調する
set cursorline

"set indent
set shiftwidth=4

set backspace=indent,eol,start

set guifont=Ricty:h18

inoremap <silent> jj <ESC>
inoremap <silent> っj <ESC>

if &compatible
  set nocompatible  
endif


" dein 
if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)
    call dein#add('Shougo/dein.vim')
    call dein#add('Shougo/neosnippet.vim')
    call dein#add('Shougo/neosnippet')
    call dein#add('Shougo/neosnippet-snippets')
    call dein#add('Shougo/unite.vim')
    call dein#add('Shougo/neocomplete.vim')
    call dein#add('vim-perl/vim-perl')

    " COLOR 
    call dein#add('altercation/vim-colors-solarized')
    call dein#add('tomasr/molokai')
    call dein#add('freeo/vim-kalisi')
    call dein#add('sjl/badwolf')

    call dein#add('scrooloose/nerdtree')
    call dein#add('jistr/vim-nerdtree-tabs')
    call dein#add('ctrlpvim/ctrlp.vim')
    call dein#add('fatih/vim-go')
    call dein#add('othree/html5.vim')
    call dein#add('tiagofumo/vim-nerdtree-syntax-highlight')


    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
end

syntax enable
set background=dark
"colorscheme solarized
"colorscheme molokai
colorscheme kalisi
let g:solarized_termcolors=256



nnoremap <silent><C-e> :NERDTreeTabsToggle<CR>

" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
exec 'autocmd FileType nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
exec 'autocmd FileType nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction
"
au VimEnter * call NERDTreeHighlightFile('yml', '44', 'none', 'green', '#151515')
au VimEnter * call NERDTreeHighlightFile('go', '115', 'none', 'yellow', '#151515')
"au VimEnter * call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
"au VimEnter * call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
"au VimEnter * call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
"au VimEnter * call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
"au VimEnter * call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
"au VimEnter * call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
"au VimEnter * call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
"au VimEnter * call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
"au VimEnter * call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
"au VimEnter * call NERDTreeHighlightFile('js', '5', 'none', '#ffa500', '#151515')
"au VimEnter * call NERDTreeHighlightFile('pl', '1', 'none', '#ffa500', '#151515')
"au VimEnter * call NERDTreeHighlightFile('md', 'Magenta', 'none', '#ff00ff', '#151515')


if argc() == 0
    let g:nerdtree_tabs_open_on_console_startup = 1
end

let g:go_fmt_command = "goimports"

let g:NERDTreeHighlightFolders = 1 " enables folder icon highlighting using exact match
let g:NERDTreeHighlightFoldersFullName = 1 " highlights the folder name





noremap! ¥ \
"noremap! \ ¥

"autocmd BufNewFile,BufRead *.py nnoremap <C-e> :!python %
"autocmd BufNewFile,BufRead *.pl nnoremap <C-e> :!perl %

