[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = 'perl'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

