[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
hook_add = '''
let g:neocomplete#enable_at_startup = 1
'''


[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = 'perl'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'nsf/gocode'
on_ft = 'go'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
